# Generated by Django 4.0.3 on 2023-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='price',
            field=models.SmallIntegerField(),
        ),
    ]
