# Generated by Django 4.0.3 on 2023-03-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_service_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Completed',
            new_name='completed',
        ),
    ]
